//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManager.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public long ID { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> AccessedDate { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<double> Size { get; set; }
        public Nullable<int> ParentDirect { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ContentFile { get; set; }
    }
}
