//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManager.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FileManagerEntities : DbContext
    {
        public FileManagerEntities()
            : base("name=FileManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileDescription> FileDescriptions { get; set; }
        public virtual DbSet<Modify> Modifies { get; set; }
        public virtual DbSet<Share> Shares { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
